name: example
description: Comparison of AdaptiveSvg (DOM) vs flutter_svg rendering.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  adaptive_svg:
    path: ../
  flutter_svg: ^2.0.17
  pointer_interceptor: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
